### ISSUE TITLE
Enable PARKIT for PWA

### ISSUE THREAD

**Issue by Acidham** [berufsbildung-basel/parkit-service#2]
To have PARKIT handy when traveling to the office, it would be useful to make PARKIT a PWA. 

https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/Add_to_home_screen

**Comment by solaris007** [comment]
resolved with commits bd4d0ff26f67045f8409f8772c71214606434be9, 40bdbf87b86c450b05048766543bc3075c657077 and 823832a8c09ac5f00c832a378dffff964961ab97
